# Generated by Django 5.1.5 on 2025-02-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
