# Generated by Django 5.1.5 on 2025-02-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cart',
            new_name='last_cart',
        ),
    ]
